language: go
go_import_path: github.com/freundallein/token-session

service:
  - docker

jobs:
  include:
    - stage: test
      name: "Unit tests"
      go: 1.13.x
      script: make test

notifications:
  on_success: never
  on_failure: never